version: "3.8"

services:

  backend:
    image: bathri98/freshcart-backend:${TAG}
    ports:
      - "5000:5000"
    networks:
      - freshcart-network

  frontend:
    image: bathri98/freshcart-frontend:${TAG}
    ports:
      - "80:80"
    networks:
      - freshcart-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: freshcart
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - freshcart-network

networks:
  freshcart-network:

volumes:
  mysql-data:
